### ISSUE TITLE
read last 5 lines… if possible

### ISSUE THREAD

**Issue by MiroslavMatas** [bogen85/CudaText_modeline_plugin#11]
I am not sure, if will be possible to add option for "find MODE_KEY" from last 5 lines…
currently - checked first 5 rows
and have no idea if reading last lines is not against _definition of modeline_

**Comment by Alexey-T** [comment]
it will be slower - e.g. imagine 2Mb C++ header. to read its ending, we need to read 2Mb and find final 5 lines.
finding LAST lines is not simple - we need to read all first lines OR find line-breaks in the last block!

and it is against 'modeline.'

**Comment by bogen85** [comment]
@MiroslavMatas I understand the desire to from the end of the file as well. And yes, It might not fit the definition in regard to how to how modeline is used in other editors.

But I agree with Alexey-T there is no simple way to do, so I had to work with what I have.

**Comment by bogen85** [comment]
@MiroslavMatas if you can find an efficient way of doing this, please make a PR and reopen this issue.

**Comment by bogen85** [comment]
@Alexey-T not sure about the existing code for this plugin then:
```python
def do_find_modeline(ed):
    nlines = min(MAX_READ_LINES, ed.get_line_count())
    lines = [ed.get_text_line(i) for i in range(nlines)]

    for index, line in enumerate(lines):
        mk_index = line.find(MODE_KEY)
        if -1 != mk_index:
            mode_message(f'{ed.get_filename()}:{index+1}: {line}')
            modeline = line[mk_index+MODE_KEY_LEN:]
            modes = cookies.SimpleCookie(modeline)
```

How does `ed.get_line_count()` determine the line count?

Is calling that already going to cause problems on large files? I've not tried it... In general any source code I work on that I'd be putting a mode line in it will be under 10 KLOC and most likely under 1000 LOC.

**Comment by bogen85** [comment]
Ok, I created a 213 KLOC source file...
![image](https://user-images.githubusercontent.com/52499484/205761774-b7030e0c-a37d-4012-9e15-bb031db2f6f4.png)
Alright, so I'll need to disable that...

**Comment by bogen85** [comment]
OK, I bumped it up to 32.
213 KLOC file.
Modified the plugin to read the last 5 lines if mode line was not found in the first 5 lines...
It finds it.
```python
cuda_modeline: CudaText: /home/dev/sandbox/lib_dasfpcpp/core00.pas:213001: // CudaText: lexer_file=Pascal; tab_size=6; tab_spaces=Yes; newline=LF;
cuda_modeline: CudaText: LEXER_FILE = Pascal
cuda_modeline: CudaText: TAB_SIZE = 6
cuda_modeline: CudaText: TAB_SPACES = True
cuda_modeline: CudaText: NEWLINE = lf
Loaded session: "history session.json", 160ms, 13 file(s) + 1 modified
Startup: 460ms, plugins: 50ms (clock 2ms, colored_indent 1ms, project_man 40ms, modeline 6ms)
Init: cudatext
```
That is on reopening 14 files, most with mode lines. The only one with the mode line at the bottom, the mode line was at line 213001.

Interesting thing though, while the session loaded in 460ms, the cursor was at bottom of the 213 KLOC file, and it took several seconds for that file to be highlighted...

**Comment by bogen85** [comment]
`core00.pas` is `6.2M`

**Comment by bogen85** [comment]
Anyways, the changes are here:
https://github.com/bogen85/CudaText_modeline_plugin/blob/last_5_feature_11/__init__.py

**Comment by bogen85** [comment]
> How does `ed.get_line_count()` determine the line count?


https://github.com/Alexey-T/CudaText/blob/master/app/formmain_py_api.inc#L1827

```pascal
function api_ed_get_line_count(Self, Args: PPyObject): PPyObject; cdecl;
var
  H: Int64;
  Ed: TATSynEdit;
begin
  with AppPython.Engine do
    if Bool(PyArg_ParseTuple(Args, 'L:get_line_count', @H)) then
    begin
      Ed:= PyHelper_EditorFromHandle(H);
      Result:= PyLong_FromLong(Ed.Strings.Count);
    end
  else
    Result:= ReturnNone;
end;
```

That looks like the entire file has already been read.

I used `ed.get_line_count()` because that is what is in the example plugin...
https://github.com/Alexey-T/CudaText/search?q=get_line_count

**Comment by bogen85** [comment]
So, I guess a couple things:
1. How do I query `ui_max_size_lexer`
2. How do I get current file size

I guess if not found in the first 5 lines, I could check if the current file size is less then `ui_max_size_lexer`, and if so, go ahead and check the last 5 lines (which I already have support for).

**Comment by bogen85** [comment]
Well, `os.path.getsize(filename)` works...
```python
mode_message(f'{filename}: {os.path.getsize(filename)} bytes')
```
As does `os.stat(filename).st_size`
```python
mode_message(f'{filename}: {os.stat(filename).st_size} bytes')
```
But cudatext already knows the size...

**Comment by bogen85** [comment]
Well, I can use `get_opt` from `cudax_lib`
```python
import cudax_lib as apx
```

And use that to query `ui_max_size_lexer`:
```python
mode_message(f'{filename}: {apx.get_opt("ui_max_size_lexer")}')
```

Which does work.

**Comment by bogen85** [comment]
Anyways, I put in the check.

If the mode line is not found in the first 5 lines, I check if the current file size is less then ui_max_size_lexer, and if so, go ahead and check the last 5 lines.

This is working.

I updated https://github.com/bogen85/CudaText_modeline_plugin/blob/last_5_feature_11/__init__.py

**Comment by bogen85** [comment]
@Alexey-T since the current implementation won't be affected by reading from the top or the bottom of the file, I'm going to merge PR #12  if you have no objection.
